### PR TITLE
Testing branch protection rules

### PR DESCRIPTION
**Pull request by cgraham-rs**
- Manually created branch protection rules in the repo settings copying what Connect currently has configured
- Attempted to push to `main` and was correctly blocked 

```
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'github.com:rstudio/jumpstart_examples.git'
```

- Created local branch
- Pushed
- Created this PR to test merge requirements
- Verified I am blocked without PR approval

image

- Verified [Collaborators and teams](https://github.com/rstudio/jumpstart_examples/settings/access) require at least [Write level permissions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-pull-request-reviews-in-your-repository) for their PR review approval to unlock the ability to merge the PR. I added Pablo as a `Read` user and I could not merge until I bumped him to at least the `Write` role.

### CODE REVIEW

**Review by plascaray — APPROVED** [review]
🚀

**Comment by cgraham-rs** [comment]
Closing. 

There are no code changes in this PR, it was purely to test branch protections which have been validated.

**Comment by ChaitaC** [comment]
@cgraham-rs, fyi: even after Pablo's approval, the PR was still blocked from merging.

**Comment by cgraham-rs** [comment]
> @cgraham-rs, fyi: even after Pablo's approval, the PR was still blocked from merging.

That was due to me deleting him from the member list entirely. He still appeared in the PR reviewer list, Github does not remove deleted member's activity. 

But I manually verified that while Pablo was a member I could not merge until his member role was at least `Write`. Then deleted him after as a final test.

**Pull request closed without merging**
